Repository 42-42-transcendence/ft_transcendence, pull requests merged in 2023-11, with the labels that each got.

#19 16 initial screen rendering
  front/package-lock.json
  front/package.json
  front/src/components/WebGPU/Shaders/fragment.wgsl
  front/src/components/WebGPU/Shaders/vertex.wgsl
  front/src/components/WebGPU/hook/useCanvasSize.ts
  front/src/components/WebGPU/hook/useWebGPU.ts
  front/src/components/WebGPU/initialize.ts
  front/src/components/WebGPU/webGPU.ts
  front/src/routes/Game.tsx
  front/src/types.d.ts
  front/src/webpack.config.js
Labels: enhancement

#22 헤더 네비게이션에서의 드랍다운 구현
  front/package-lock.json
  front/public/index.html
  front/src/UI/Modal.tsx
  front/src/components/Navigation/IconList.tsx
  front/src/components/Navigation/NotificationDropdown.tsx
  front/src/components/Navigation/UserDropdown.tsx
  front/src/components/WebGPU/hook/useCanvasSize.ts
  front/src/routes/Game.tsx
  front/src/routes/index.tsx
  front/src/styles/Dropdown.module.css
  front/src/styles/Modal.module.css
  front/src/styles/Navigation.module.css
  front/src/styles/Sidebar.module.css
  front/tsconfig.json
Labels: enhancement

#25 누락된 채팅방 아이콘 수정
  front/src/assets/add-user-icon.svg
  front/src/assets/default-avatar.png
  front/src/assets/exit-icon.svg
  front/src/assets/logout-icon.tsx
  front/src/assets/notification-icon.svg
  front/src/assets/notification-icon.tsx
  front/src/assets/setting-icon.svg
  front/src/assets/settings-icon.tsx
  front/src/assets/user-icon.svg
  front/src/assets/user-icon.tsx
  front/src/components/Chatting/ChattingContents.tsx
  front/src/components/Chatting/ChattingSettingList.tsx
  front/src/components/Chatting/ChattingSettingsButton.tsx
  front/src/components/Chatting/SystemMessageItem.tsx
  front/src/components/Chatting/index.tsx
  front/src/components/Navigation/IconList.tsx
  front/src/components/Navigation/NotificationDropdown.tsx
  front/src/styles/Chatting.module.css
  front/src/styles/Navigation.module.css
Labels: enhancement

#32 26 modal
  front/package-lock.json
  front/package.json
  front/src/UI/UserItem.tsx
  front/src/components/Channel/ChannelSidebar.tsx
  front/src/components/Channel/index.tsx
  front/src/components/Chatting/ChattingMemberItem.tsx
  front/src/components/Chatting/ChattingMemberList.tsx
  front/src/components/Chatting/ChattingSettingList.tsx
  front/src/components/Chatting/index.tsx
  front/src/components/Friends/FriendItem.tsx
  front/src/components/Friends/FriendList.tsx
  front/src/components/Friends/FriendsSidebar.tsx
  front/src/components/Friends/index.tsx
  front/src/components/GameMode/GameModeForm.tsx
  front/src/components/GameModeForm/GameModeSelectionList.tsx
  front/src/components/GameModeForm/index.tsx
  front/src/components/Modal/AchievementDetailModal.tsx
  front/src/components/Modal/AddFriendModal.tsx
  front/src/components/Modal/ChatExitConfirmModal.tsx
  front/src/components/Modal/ChatInvitationModal.tsx
  front/src/components/Modal/ChatMemberDetailModal.tsx
  front/src/components/Modal/ChatRoomConfigModal.tsx
  front/src/components/Modal/CreatingChatRoomModal.tsx
  front/src/components/Modal/FriendDetailModal.tsx
  front/src/components/Modal/FriendRequestModal.tsx
  front/src/components/Modal/GameInvitationModal.tsx
  front/src/components/Modal/GameMatchingModal.tsx
  front/src/components/Modal/useCloseModal.ts
  front/src/components/Modal/useModalState.ts
  front/src/components/Modal/useOpenModal.ts
  front/src/components/Navigation/NotificationDropdown.tsx
  front/src/components/Profile/AchievementItem.tsx
  front/src/components/Profile/index.tsx
  front/src/index.tsx
  front/src/routes/Chatting.tsx
  front/src/routes/Game.tsx
  front/src/routes/Main.tsx
  front/src/routes/index.tsx
  front/src/store/ReduxProvider.tsx
  front/src/store/index.ts
  front/src/store/modal.ts
  front/src/styles/Channel.module.css
  front/src/styles/Dashboard.module.css
  front/src/styles/Friends.module.css
  front/src/styles/GameSelect.module.css
  front/src/styles/Modal.module.css
  front/src/styles/ToggleRadioButton.module.css
Labels: enhancement

#37 OAuth / 전역 상태 / 라우트 가드 구현
  front/package-lock.json
  front/package.json
  front/src/components/Navigation/NavList.tsx
  front/src/components/Navigation/UserDropdown.tsx
  front/src/routes/Game.tsx
  front/src/routes/Login.tsx
  front/src/routes/OAuth.tsx
  front/src/routes/ProtectedRouter.tsx
  front/src/routes/RootLayout.tsx
  front/src/routes/SettingProfile.tsx
  front/src/routes/TwoFactorAuth.tsx
  front/src/routes/index.tsx
  front/src/store/ReduxProvider.tsx
  front/src/store/auth.ts
  front/src/store/index.ts
  front/src/styles/Login.module.css
Labels: enhancement

#43 31 pong game implement
  front/package-lock.json
  front/package.json
  front/src/components/WebGL/function/gameLoop.ts
  front/src/components/WebGL/function/initialize.ts
  front/src/components/WebGL/function/render.ts
  front/src/components/WebGL/function/shader.ts
  front/src/components/WebGL/function/update.ts
  front/src/components/WebGL/hook/useCanvasSize.ts
  front/src/components/WebGL/interface/gameData.ts
  front/src/routes/Game.tsx
  front/src/routes/index.tsx
  front/src/types.d.ts
Labels: enhancement

#46 44 game refact
  front/src/components/WebGL/function/gameLoop.ts
  front/src/components/WebGL/function/initialize.ts
  front/src/components/WebGL/function/render.ts
  front/src/components/WebGL/function/update.ts
Labels: refact

#53 channel 접근 여부 확인 및 접근 시도
  backend/src/auth/auth.controller.ts
  backend/src/channel/channel.controller.ts
  backend/src/channel/channel.service.ts
  backend/src/channel/entities/channel.entity.ts
  backend/src/channel/enums/channelType.enum.ts
  backend/src/chat/entities/chat.entity.ts
  backend/src/user/entities/user.entity.ts
Labels: enhancement

#57 backend socket.io(websocket) 붙여보기
  backend/package-lock.json
  backend/package.json
  backend/src/adapters/socket-io.adapter.ts
  backend/src/app.module.ts
  backend/src/auth/auth.module.ts
  backend/src/channel/channel.controller.ts
  backend/src/channel/channel.module.ts
  backend/src/channel/enums/channelType.enum.ts
  backend/src/events/events.gateway.ts
  backend/src/events/events.module.ts
  backend/src/main.ts
Labels: enhancement

#58 프론트 소켓 연결 구현 (with Context)
  front/package-lock.json
  front/package.json
  front/src/App.tsx
  front/src/components/Channel/ChannelItem.tsx
  front/src/components/Channel/ChannelList.tsx
  front/src/components/Channel/index.tsx
  front/src/components/Chatting/index.tsx
  front/src/components/Modal/ChatPasswordModal.tsx
  front/src/components/Navigation/UserDropdown.tsx
  front/src/index.tsx
  front/src/routes/Chatting.tsx
  front/src/routes/ProtectedRouter.tsx
  front/src/routes/index.tsx
  front/src/socket/SocketContext.tsx
  front/src/store/Auth/auth.ts
Labels: documentation, enhancement

#65 채팅 관련 소켓 및 API 구현 완료
  Dockerfile
  Makefile
  README.md
  front/src/App.tsx
  front/src/components/Channel/ChannelItem.tsx
  front/src/components/Channel/index.tsx
  front/src/components/Chatting/ChattingContents.tsx
  front/src/components/Chatting/ChattingForm.tsx
  front/src/components/Chatting/ChattingMemberItem.tsx
  front/src/components/Chatting/ChattingMemberList.tsx
  front/src/components/Chatting/ChattingMessageItem.tsx
  front/src/components/Chatting/ChattingMessageList.tsx
  front/src/components/Chatting/ChattingSettingList.tsx
  front/src/components/Chatting/index.tsx
  front/src/components/Friends/index.tsx
  front/src/components/Modal/ChatInvitationModal.tsx
  front/src/components/Modal/ChatMemberDetailModal.tsx
  front/src/components/Modal/ChatRoomConfigModal.tsx
  front/src/components/Modal/ConfirmModal.tsx
  front/src/components/Modal/CreatingChatRoomModal.tsx
  front/src/components/Modal/FriendDetailModal.tsx
  front/src/components/Modal/MessageModal.tsx
  front/src/components/Modal/UserDetailModal.tsx
  front/src/components/Navigation/NavList.tsx
  front/src/components/Navigation/NotificationDropdown.tsx
  front/src/components/Navigation/UserDropdown.tsx
  front/src/components/Navigation/index.tsx
  front/src/components/Social/SocialIconList.tsx
  front/src/components/Social/SocialList.tsx
  front/src/components/Social/SocialSidebar.tsx
  front/src/components/Social/SocialUserItem.tsx
  front/src/components/Social/index.tsx
  front/src/http/useRequest.ts
  front/src/routes/Chatting.tsx
  front/src/routes/Friends.tsx
  front/src/routes/OAuth.tsx
  front/src/routes/Profile.tsx
  front/src/routes/ProtectedRouter.tsx
  front/src/routes/RootLayout.tsx
  front/src/routes/SettingProfile.tsx
  front/src/routes/Social.tsx
  front/src/routes/index.tsx
  front/src/socket/SocketContext.tsx
  front/src/store/Auth/auth.ts
  front/src/store/Modal/modal.ts
  front/src/styles/Chatting.module.css
  front/src/styles/Dropdown.module.css
  front/src/styles/Modal.module.css
  front/src/styles/Social.module.css
Labels: enhancement

#68 User API 관련 로직 구현
  front/src/components/Channel/ChannelList.tsx
  front/src/components/Channel/index.tsx
  front/src/components/Chatting/ChattingForm.tsx
  front/src/components/Chatting/ChattingMessageItem.tsx
  front/src/components/Chatting/index.tsx
  front/src/components/Dashboard/DashboardItem.tsx
  front/src/components/Dashboard/DashboardList.tsx
  front/src/components/Dashboard/RecodeItem.tsx
  front/src/components/Dashboard/RecodeList.tsx
  front/src/components/Dashboard/index.tsx
  front/src/components/Modal/AddFriendModal.tsx
  front/src/components/Modal/ChatInvitationModal.tsx
  front/src/components/Modal/ChatPasswordModal.tsx
  front/src/components/Modal/ChatRoomConfigModal.tsx
  front/src/components/Modal/CreatingChatRoomModal.tsx
  front/src/components/Modal/UserDetailModal.tsx
  front/src/components/Navigation/IconList.tsx
  front/src/components/Profile/AchievementItem.tsx
  front/src/components/Profile/index.tsx
  front/src/components/SettingProfile/AvatarInput.tsx
  front/src/components/SettingProfile/NameInput.tsx
  front/src/components/SettingProfile/SettingProfileForm.tsx
  front/src/components/Social/SocialIconList.tsx
  front/src/components/Social/SocialList.tsx
  front/src/components/Social/SocialSidebar.tsx
  front/src/components/Social/SocialUserItem.tsx
  front/src/components/Social/index.tsx
  front/src/routes/Chatting.tsx
  front/src/routes/Dashboard.tsx
  front/src/routes/OAuth.tsx
  front/src/routes/SettingProfile.tsx
  front/src/routes/index.tsx
  front/src/store/Auth/auth.ts
  front/src/styles/Chatting.module.css
  front/src/styles/Dashboard.module.css
  front/src/styles/Modal.module.css
  front/src/styles/Navigation.module.css
  front/src/styles/SettingProfileForm.module.css
  front/src/styles/Social.module.css
  front/src/styles/index.css
Labels: enhancement

#74 프론트 Notification 구현 완료
  front/src/components/Navigation/IconList.tsx
  front/src/components/Navigation/NotificationDropdown.tsx
  front/src/components/Navigation/NotificationItem.tsx
  front/src/socket/SocketContext.tsx
  front/src/store/Notification/notification.ts
  front/src/store/Notification/useNotificationState.ts
  front/src/store/index.ts
  front/src/styles/Dropdown.module.css
Labels: enhancement

#80 채널 비밀번호 암호화
  backend/package-lock.json
  backend/package.json
  backend/src/channel/channel.controller.ts
  backend/src/channel/channel.repository.ts
Labels: enhancement
