Repository 42-42-transcendence/ft_transcendence, pull requests merged in 2023-12, with the labels that each got.

#88 게임 초대, 매칭 시스템
  backend/package-lock.json
  backend/src/events/events.gateway.ts
  backend/src/events/events.service.ts
  backend/src/game/enums/gameMode.enum.ts
  backend/src/game/game.controller.ts
  backend/src/game/game.engine.ts
  backend/src/game/game.module.ts
  backend/src/game/game.service.ts
  backend/src/main.ts
  backend/src/notification/dto/notification-with-data.dto.ts
  backend/src/notification/enums/noti-type.enum.ts
  backend/src/notification/notification.repository.ts
  backend/src/notification/notification.service.ts
  backend/src/user/user.service.ts
Labels: enhancement

#91 멀티 페이지(로그인) 막기
  backend/src/events/events.gateway.ts
  backend/src/events/events.service.ts
  backend/src/events/socket.filter.ts
Labels: enhancement

#98 소켓 구조 변경 및 AI mode 설정
  front/src/components/GameModeForm/GameModeSelectionList.tsx
  front/src/components/GameModeForm/index.tsx
  front/src/components/Modal/GameMatchingModal.tsx
  front/src/components/Modal/GameResultModal.tsx
  front/src/components/WebGL/class/AIManager.ts
  front/src/components/WebGL/class/Ball.ts
  front/src/components/WebGL/class/GameManager.ts
  front/src/components/WebGL/class/GameObject.ts
  front/src/components/WebGL/class/Item.ts
  front/src/components/WebGL/class/ItemManager.ts
  front/src/components/WebGL/class/Paddle.ts
  front/src/components/WebGL/class/PhysicsEngine.ts
  front/src/components/WebGL/context/SocketContext.tsx
  front/src/components/WebGL/function/gameLoop.ts
  front/src/components/WebGL/function/initialize.ts
  front/src/components/WebGL/function/receive.ts
  front/src/components/WebGL/function/render.ts
  front/src/components/WebGL/function/update.ts
  front/src/components/WebGL/hook/useBeforeunload.ts
  front/src/components/WebGL/hook/useGameEvent.ts
  front/src/components/WebGL/hook/usePopstate.ts
  front/src/components/WebGL/hook/usePress.ts
  front/src/components/WebGL/interface/gameData.ts
  front/src/routes/Game.tsx
  front/src/routes/index.tsx
  front/src/socket/SocketContext.tsx
  front/src/types.d.ts
Labels: enhancement

#105 104 game server link part adjustment
  front/src/components/Modal/GameMatchingModal.tsx
  front/src/components/WebGL/class/AIManager.ts
  front/src/components/WebGL/class/GameManager.ts
  front/src/components/WebGL/class/GameObject.ts
  front/src/components/WebGL/class/PhysicsEngine.ts
  front/src/components/WebGL/context/SocketContext.tsx
  front/src/components/WebGL/function/gameLoop.ts
  front/src/components/WebGL/function/update.ts
  front/src/routes/Game.tsx
  front/src/socket/SocketContext.tsx
Labels: enhancement, refact

#110 친구 추가, 삭제
  backend/src/channel/channel.controller.ts
  backend/src/channel/channel.module.ts
  backend/src/events/events.module.ts
  backend/src/relation/dto/social.dto.ts
  backend/src/relation/relation.controller.ts
  backend/src/relation/relation.module.ts
  backend/src/relation/relation.repository.ts
  backend/src/relation/relation.service.ts
  backend/src/user/user.module.ts
Labels: enhancement

#120 OAuth 도중 새로고침 시 exception 해결
  backend/src/auth/auth.service.ts
Labels: bug

#127 프론트 패키지 최신화
  front/package-lock.json
  front/package.json
  front/src/components/SettingProfile/SettingProfileForm.tsx
  front/src/routes/Otp.tsx
  front/src/routes/ProtectedRouter.tsx
Labels: refact

#131 129 image volume n message load issue
  backend/assets/defaults/default.jpeg
  backend/src/chat/chat.repository.ts
  backend/src/chat/chat.service.ts
  backend/src/events/events.gateway.ts
  backend/src/user/entities/user.entity.ts
  docker-compose.yml
Labels: enhancement

#132 130 front 채팅 관련 로직 수정
  front/src/components/Chatting/index.tsx
Labels: enhancement

#139 FIX: front, backend 요구사항 수정
  backend/src/game/game.controller.ts
  front/src/components/Navigation/GameInvitationItem.tsx
  front/src/store/Notification/notification.ts
Labels: bug
